/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#474556",
        "error-container": "#ffdad6",
        "ink-secondary": "#273951",
        "brand-dark-900": "#1c1e54",
        hairline: "#e3e8ee",
        "primary-fixed": "#e3dfff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3600e1",
        "on-background": "#1b1a25",
        "primary-press": "#2e2b8c",
        "inverse-surface": "#302f3a",
        magenta: "#f96bee",
        "primary-deep": "#4434d4",
        "secondary-fixed-dim": "#b2c8e7",
        "outline-variant": "#c8c4da",
        "inverse-primary": "#c5c0ff",
        "surface-container-high": "#eae6f5",
        "surface-tint": "#5036fa",
        "on-primary-fixed": "#130067",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3eefe",
        "surface-variant": "#e4e0ef",
        "primary-container": "#533afd",
        "on-error": "#ffffff",
        "surface-bright": "#fcf8ff",
        "on-secondary-container": "#4d627d",
        "secondary-fixed": "#d2e4ff",
        "primary-bg-subdued": "#b9b9f9",
        secondary: "#4a607b",
        ruby: "#ea2261",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e4e0ef",
        "primary-soft": "#665efd",
        "surface-container": "#f0ecfb",
        surface: "#fcf8ff",
        primary: "#3904e7",
        "on-surface": "#1b1a25",
        "ink-mute": "#64748d",
        tertiary: "#464a4d",
        "on-error-container": "#93000a",
        lemon: "#9b6829",
        background: "#fcf8ff",
        outline: "#777588",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "primary-fixed-dim": "#c5c0ff",
        "surface-dim": "#dcd8e7",
        "tertiary-container": "#5e6265",
        "secondary-container": "#c8dffe",
        "surface-container-low": "#f6f2ff",
        "canvas-cream": "#f5e9d4",
        "on-primary-container": "#ddd9ff",
        "canvas-soft": "#f6f9fc",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        md: "12px",
        xl: "24px",
        sm: "8px",
        lg: "16px",
        xxl: "32px",
        xxs: "2px",
        huge: "64px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
    },
  },
  plugins: [],
};
